apiVersion: v1
kind: Pod
metadata:
  name: kind-worker3
  namespace: mem-example
spec:
  containers:
  - name: kind-worker3
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]