---
all:
 vars:
   # changes according to requirements
   zone: asia-southeast2-a
   region: asia-southeast2
   project_id: cmlabs-123456 #enter you project id
   gcloud_sa_path: "~/gcpserviceaccount.json" # Enter path to you service account json file
   gcloud_service_account: "service-account@project-id.iam.gserviceaccount.com"
   credential: "{{lookup('env','HOME') }}/{{gcloud_sa_path}}"
   maxvalue: 6
   minvalue: 3
   cpuscale: "50%"

   #Cluster information
   cluster_name: "production" #Name of the cluster
   initial_node_count: 2   #Number of node for cluster
   disk_size_gb: 100
   disk_type: "pd-ssd"  #disk types 
   machine_type: "e2-standard-2"  #image types